### ISSUE TITLE
Stack size flag (-Xss) not set explicitly by default

### ISSUE THREAD

**Issue by TimGerlach** [cloudfoundry/java-buildpack-memory-calculator#10]
It looks like the memory calculator considers a [default stack size of 1M](https://github.com/cloudfoundry/java-buildpack-memory-calculator/blob/master/memory/allocator.go#L104-L108) for the calculation, if `-Xss` is not set in JAVA_OPTS manually by developers. However, if this default value is used, no `-Xss` flag is ever given to the JVM which leads to the default stack size being used by the JVM.

It's probably a minor issue since most JVMs use less than or exactly 1M as stack size by default (e.g. OpenJDK JRE), but it's a potential inconsistency between the memory calculation and the actual limit taken into account during runtime. Also, when the JVM uses a default stack size less than 1M, e.g. when using a different JRE, the memory calculator considers too much memory for stacks (stack size * stack threads).

Therefore, and for the sake of transparency, I think it would make sense to add `-Xss1024k` explicitly in case the memory calculator uses its default value.

What do you think?

**Comment by nebhale** [comment]
Yep, sounds right to me.

**Comment by glyn** [comment]
Nice catch @TimGerlach!

**Comment by glyn** [comment]
Fixed to add `-Xss1m` if and only if the memory calculator uses the default stack size value.
