### ISSUE TITLE
GC parallelism tweaks

### ISSUE THREAD

**Issue by jtwaleson** [cloudfoundry/java-buildpack-memory-calculator#14]
I recently read [this article](https://jaxenter.com/nobody-puts-java-container-139373.html) which points out that the garbage collector might need to be tuned (`XX:ParallelGCThreads` `XX:ConcGCThreads`) to the number of CPUs in containers. Any thoughts about including this in the memory calculator?

**Comment by nebhale** [comment]
We've not seen this being a huge problem at the moment, so I'm not inclined to make a change here.  If you're having trouble `cf set-env <APP> JAVA_OPTS '...'` will give you the behavior you want, but until we start seeing people getting enough unanticipated threads that they get OOMs, I think week hold fire.

**Comment by glyn** [comment]
Closing for now. Please re-open if necessary.
