### ISSUE TITLE
Rationale behind the reserved code cache increase with Java 8

### ISSUE THREAD

**Issue by robertofpaf** [cloudfoundry/java-buildpack-memory-calculator#16]
Hello,

The calculator's README file states that:

> For Java 8 and later, the memory calculator sets the maximum metaspace size (-XX:MaxMetaspaceSize) based on the number of classes that will be loaded and sets the reserved code cache size (-XX:ReservedCodeCacheSize) to 240 Mb.
>
> For Java 7, it sets the maximum permanent generation size (-XX:MaxPermSize) based on the number of classes that will be loaded and sets the reserved code cache size (-XX:ReservedCodeCacheSize) to 48 Mb.

And also the linked google document states:

> Memory calculator v3 estimates:
> - maximum metaspace size
> - compressed class space size
>
> based on the number of class files in the application. It sets the following to constants:
> - reserved code cache size (48 Mb on Java 7; 240 Mb on Java 8)
> - maximum direct memory size (10 Mb)
> and then sets the heap size to the remainder of total memory.

But the rationale behind the increase of reserved code cache from 48 Mb to 240 Mb is not explained anywhere. Would it be possible to explain it?

Thanks in advance!

**Comment by TimGerlach** [comment]
https://github.com/cloudfoundry/java-buildpack/issues/392 as well as https://github.com/cloudfoundry/java-buildpack/issues/513 might help you.

**Comment by nebhale** [comment]
@robertofpaf @TimGerlach’s links are good context for us discussing the outcome of the changes and why we don’t want to change it, but (surprisingly) doesn’t actually discuss the root of the change itself.  The long and short of it is that we didn’t make the call.  The change from 48M (on some architectures, it was 100M on others) to 240M was made by the JVM development team.  We’ve only ensured that the memory calculator honors those defaults, not made the decision ourselves.  I cannot remember where exactly I read it, but I believe that the change was made to support the Tiered Compilation in the JIT.

**Comment by robertofpaf** [comment]
@nebhale Thanks, this clarified!
