### ISSUE TITLE
Create a binary release for using independently of the platform

### ISSUE THREAD

**Issue by amitizle** [cloudfoundry/java-buildpack-memory-calculator#19]
Thanks for this solution!

Maybe you can use a Github release and/or [goreleaser](https://github.com/goreleaser/goreleaser).

The use case is: starting a container in _Kubernetes_ / `docker-compose` it will be nice to have a bash script running `java -cp ...` and appending the options generated by this app, just by `curl`ing for the binary and using it.

**Comment by nebhale** [comment]
We do publish to an [Artifactory instance](https://repo.spring.io/list/release/org/cloudfoundry/java-buildpack-memory-calculator/) as part of our [CI](https://java-experience.ci.springapps.io/teams/java-experience/pipelines/memory-calculator/jobs/build-release/builds/14).  Is this sufficient for your needs?

**Comment by amitizle** [comment]
That's perfect thanks @nebhale.
In case anyone wants to get the binary in the future:
```bash
#!/usr/bin/env bash

BASE_URL="https://repo.spring.io/list/release/org/cloudfoundry/java-buildpack-memory-calculator"
MEMORY_CALCULATOR_VERSION="${MEMORY_CALCULATOR_VERSION:-3.13.0}"
MEMORY_CALCULATOR_OS="${MEMORY_CALCULATOR_OS:-linux}" # or darwin

# WARN --transform is not supported in BSD tar (= mac/darwin)
curl -L \
  "${BASE_URL}/${MEMORY_CALCULATOR_VERSION}.RELEASE/java-buildpack-memory-calculator-${MEMORY_CALCULATOR_VERSION}.RELEASE-${MEMORY_CALCULATOR_OS}.tar.gz" | \
  tar -xz --transform="s/java-buildpack-memory-calculator-${MEMORY_CALCULATOR_OS}/java-buildpack-memory-calculator/" 
```
Script can be improved though.

Closing
