### ISSUE TITLE
Documented formula for estimating metaspace appears to be incorrect

### ISSUE THREAD

**Issue by vpavic** [cloudfoundry/java-buildpack-memory-calculator#23]
The document [Java Buildpack Memory Calculator v3](https://docs.google.com/document/d/1vlXBiwRIjwiVcbvUGYMrxx2Aw1RVAtxq3iuZ3UK2vXA/edit?usp=sharing) linked in project's readme contains the following formula for estimating metaspace:

```
5400 * (number of loaded casses) + 7000000
```

This appears to be out of sync with:

https://github.com/cloudfoundry/java-buildpack-memory-calculator/blob/beef546da73761e7d1e1cfaacac6ff8655ad40aa/calculator/calculator.go#L103-L105

**Comment by nebhale** [comment]
Yeah, that's what it was with [permgen based versions](https://github.com/cloudfoundry/java-buildpack-memory-calculator/blob/v3.13.0.RELEASE/memory/allocator.go#L70) although even that hasn't kept up with our evolution.
