### ISSUE TITLE
Getting java.lang.OutOfMemoryError: Java heap space when using Spring kafka to produce a message

### ISSUE THREAD

**Issue by rajeshhereforyou** [cloudfoundry/java-buildpack-memory-calculator#27]
I'm trying to deploy a spring boot app on Pivotal Cloud Foundry to use spring kafka to send a message to kafka and getting below error with 1GB memory in manifest.yml. My sprint boot app has just one Rest Controller with only one endpoint to send a message. The app is starting without any issue if I change the memory to 2GB in my manifest.yml and it's taking almost 1.3 GB - 1.8 GB to run the app. I'm wondering why this simple app is taking so much more. Is it because of Kafka ?
In our app, we are using org.apache.kafka.clients.admin.KafkaAdminClient

We are using Spring 2.x, java 8 and buildpack 3.9 with this app.

```
[APP/PROC/WEB/0] OUT # java.lang.OutOfMemoryError: Java heap space
 {APP/PROC/WEB/0] OUT # -XX:OnOutOfMemoryError="/home/vcap/app/.java-buildpack/open_jdk_jre/bin/killjava.sh"
```

Any help to understand this issue would be greatly appreciated.

**Comment by nebhale** [comment]
Each application has its own memory profile.  It appears that given a 1GB container (which likely results in ~400M of heap after all of the memory regions are allocated), your application requires more heap than is available.  I'd hook a profiler like [YourKit](https://github.com/cloudfoundry/java-buildpack/blob/master/docs/framework-your_kit_profiler.md) or [JProfiler](https://github.com/cloudfoundry/java-buildpack/blob/master/docs/framework-jprofiler_profiler.md) to the application to determine where your memory usage is occurring.
