### ISSUE TITLE
Does option "--head-room" represents "native" memory

### ISSUE THREAD

**Issue by boyan-velinov** [cloudfoundry/java-buildpack-memory-calculator#30]
Hi,

Can you confirm that option `--head-room` represents the "native" memory defined in the document https://docs.google.com/document/d/1vlXBiwRIjwiVcbvUGYMrxx2Aw1RVAtxq3iuZ3UK2vXA/edit#

The terms do not match perfectly between README and the the document Java Buildpack Memory Calculator v3.

Best Regards,
Boyan

**Comment by nebhale** [comment]
Not directly no.  Native in the research document would include both unaccounted for memory in the JVM as well as direct memory.  Headroom in the memory calculator flags doesn't directly map to any memory region, but rather "I know what I'm doing, remove this from the memory calculation, and work from there".  It can be used to cover the JVM's C-allocated memory, but also could be used to make space for a second process to run within a container, memory for a native library being called by your application, etc.  You might view it as the escape hatch for all the scenarios we don't cover directly.

**Comment by boyan-velinov** [comment]
Thanks for the answer and Happy New Year :)
