### ISSUE TITLE
Heuristics to compute Xms (min heap size) value

### ISSUE THREAD

**Issue by icidel** [cloudfoundry/java-buildpack-memory-calculator#31]
The min heap size (aka "-Xms") value is an important value on startup: keeping the default value (128 MB) implies slow startup times when all classes loaded at startup cannot fit in this pre-allocated memory space.

It can even be the main cause of OutOfMemory errors if the growth rate is higher than the JVM/container ability to allocate more memory on-demand.

Could you try to create some heuristics to compute the min heap size according to the number of classes to load ?

**Comment by nebhale** [comment]
We used to have behavior for calculating `Xms` and removed it in version 3 (maybe 2?) of the calculator.  In the end, customers generally complained that pre-allocating memory in this way caused things like statistics about container size, auto-scaling of instances, and over-provisioning of Diego cells to behave poorly.  Given that the alternative to having this was `cf set-env <APP> JAVA_OPTS '-Xms<value>'`, we decided to remove it completely.

What kind of heuristics would you think might make sense if we were to reintroduce it?

**Comment by nebhale** [comment]
Since there's been no response on this issue in a couple of weeks, I'm going to close it.  If you'd like to see it re-opened, please comment on the issue and I'll reopen it.

**Comment by icidel** [comment]
The min heap size should ideally be the new+old memory allocated when the
server is idle.

Having a way to store this value somewhere would be a must to speed up
subsequent startups and optimize garbage collector (especially G1)
according to the real behavior.

A rough estimation can be done at first startup by setting the minimum heap
size to the number of .class files x (16 + 4) bytes.
