### ISSUE TITLE
Take garbage collector into account

### ISSUE THREAD

**Issue by Grannath** [cloudfoundry/java-buildpack-memory-calculator#35]
Hi,

I'm incredibly grateful for this project, but I encountered an unexpected problem yesterday. I was deploying a container with settings following this project. But the container kept going OOM. When observing the JVM process, there was a difference of 300MB to 400MB between the rrs value reported by `ps` and the sum of JVM memory areas, on a 3GB heap with Java 11. All limits were enforced.

From what I can tell, this was memory used by the garbage collector G1. This difference was significantly smaller for parallel and serial GCs, with a minimum of 50MB to 100MB for parallel GC. It seems that the GC does not limit itself, or simply cannot work with less than these values.

I understand that it is very difficult, maybe impossible, to predict these values. But maybe it's possible to at least gather data on this for documentation purposes. Right now, even using all of the heuristics in this project, I still have to guess for the right amount of headroom in a trial-and-error process.

**Comment by dmikusa-pivotal** [comment]
Thanks for reaching out. It's tricky to comment without some details about where the memory was being used. When you have situations like this, I would suggest doing the following:

1. Bump your memory limit up
2. Set the headroom to take up the amount you've increased the memory limit. This should give your app the same amount of memory but have a buffer of unallocated space to prevent your container from crashing.
3. Enable Java NMT and watch the memory usage, in particular as you approach the old memory limit and go past it. Java NMT is very detailed so it'll show you exactly where memory is growing and from there you can see exactly why you're going over the limit.

This is a pretty old issue (so sorry for the late reply). If you or someone else are still experiencing issues please follow the steps above, open a new issue and attach a few Java NMT diff's, making sure to indicate what your new & old memory limits are so we can see what is using up the memory. Thanks!
