### ISSUE TITLE
Documentation link in readme is broken

### ISSUE THREAD

**Issue by segaura** [cloudfoundry/java-buildpack-memory-calculator#41]
Page is this: https://github.com/cloudfoundry/java-buildpack-memory-calculator
Text is this: Java Buildpack Memory Calculator v3
Link is this: https://docs.google.com/document/d/1vlXBiwRIjwiVcbvUGYMrxx2Aw1RVAtxq3iuZ3UK2vXA/edit?usp=sharing

Following the link results in google service telling that the document is no more available.

**Comment by dmikusa-pivotal** [comment]
Apologizes. It is distinctly possible that the file is gone, lost in the Pivotal -> VMware acquisition.

I don't know what was in the doc, or I'd try to recreate it. Do you feel like there is something missing from what is in the readme? Any additional context that you'd like to understand? I will remove the broken link, but I can try to expand on anything if you feel there are gaps.

Thanks

**Comment by dmikusa-pivotal** [comment]
Removed: https://github.com/cloudfoundry/java-buildpack-memory-calculator/commit/f4e379c09e838b1c613ffe849b2f61684b814cef

**Comment by segaura** [comment]
I'm a newcomer here so I still have no feedback regarding readme, sorry.

**Comment by nipr-jdoenges** [comment]
FYI, having run into the same broken link here https://spring.io/blog/2019/03/11/memory-footprint-of-the-jvm, it sounds like the lost document was a design document for version 3.
